env:
  node: true
  es2021: true
extends:
  - airbnb-typescript/base
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - '*.js'
rules:
  '@typescript-eslint/no-unused-vars':
  - error
  - argsIgnorePattern: '^_'
    varsIgnorePattern: '^_'
  import/no-unresolved: off
  no-unused-vars: off
  sort-imports: off
  import/order: error
  '@typescript-eslint/naming-convention':
  - error
  - selector: 
    - typeLike
    format: 
    - PascalCase
    filter: 
      regex: ^iTunes
      match: false
  
